OCAMLMAKEFILE = ../../OCamlMakefile
SOURCES = ../../common/integer.ml ../bound.ml ../dashDot.ml cylindricalRegion.ml test.ml
RESULT = main
ANNOTATE = true
DOC_FILES = cylindricalRegion.ml

all: dnc

include $(OCAMLMAKEFILE)
