#load "enum.cmo";;
#load "pMap.cmo";;
#load "Nat.cmo";;
#load "Seq.cmo";;
#load "pSet.cmo";;
#load "pPos.cmo";;
#load "Prebox.cmo";;
#load "Predel.cmo";;
#load "Space.cmo";;
#load "sSet.cmo";;
#load "cSet.cmo";;
#load "HyperRect.cmo";;
module H = HyperRect;;
let x = H.interval [0;0] [2;2];;
let y = H.interval [1;-1] [10;1];;
let z = H.interval [1;1] [10;5];;
let xyz = H.union z (H.union x y);;
let lats = PSet.map H.tex (H.lattices xyz);;
let min = PSet.choice (H.min xyz);;
let poset = PPos.map Nat.tex (PPos.ord (Nat.mag 6));;
