OCAMLMAKEFILE = ../OCamlMakefile
COMMON = ../common/
INTERVAL = ../legacy/trunk_common/
SOURCES = bound.ml dashDot.ml $(COMMON)integer.ml $(INTERVAL)interval.mli $(INTERVAL)interval.ml  test.ml
RESULT = main
ANNOTATE = true
DOC_FILES = bound.ml dashDot.ml
PACKS = str

all: dnc

include $(OCAMLMAKEFILE)
